### ISSUE TITLE
Ground anchors not set in b2JointDef

### ISSUE THREAD

**Issue by einarnordengren** [d954mas/defold-box2d#19]
https://github.com/d954mas/defold-box2d/blob/4a04b48296cd33c0927021f939045fab055a32f6/box2d/native/src/joint_def.cpp#L238-L241

Why aren't groundAnchorA and groundAnchorB set here? When I create a pulley joint using InitializePulleyJointDef, my ground anchors aren't used. Instead, the default ones from b2_pulley_joint.h are used.

**Comment by d954mas** [comment]
Thanks. Looks like a bug(

I will look on in weekends.

**Comment by d954mas** [comment]
Fixed. Check this version
https://github.com/d954mas/defold-box2d/archive/refs/tags/1.0.2.zip

**Comment by einarnordengren** [comment]
Yep, it works now. Thanks.
